#-------------------------------------------------------------------------------
# POWERLEVEL10K

source ~/lib/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source ~/.p10k.zsh

#-------------------------------------------------------------------------------
# AUTO GENERATED BY CONDA

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/elliotwaite/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/elliotwaite/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/elliotwaite/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/elliotwaite/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/Users/elliotwaite/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "/Users/elliotwaite/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

#-------------------------------------------------------------------------------
# AUTO GENERATED BY PNPM

# pnpm
export PNPM_HOME="/Users/elliotwaite/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

#-------------------------------------------------------------------------------
# AUTO GENERATED BY RUST

. "$HOME/.cargo/env"

#-------------------------------------------------------------------------------
# MY CUSTOM SETTINGS

# Custom key bindings:
bindkey ';9D' backward-word # Cmd + Left -> Go to beginning of line. (iTerm)
bindkey ';9C' forward-word # Cmd + Right -> Go to end of line. (iTerm)
bindkey ';4D' backward-kill-word # Alt + Shift + Left -> Delete the word to the left. (VS Code)
bindkey ';4C' kill-word # Alt + Shift + Right -> Delete the word to the right. (VS Code)
bindkey ';2D' backward-delete-char # Shift + Left -> Delete the character to the left. (VS Code)
bindkey ';2C' delete-char # Shift + Right -> Delete the character to the right. (VS Code)
bindkey ';5D' backward-kill-line # Cmd + Shift + Left -> Delete to start of line. (VS Code, custom escape sequence: "\u001b[1;5D")
bindkey ';5C' kill-line # Cmd + Shift + Right -> Delete to end of line. (VS Code, custom escape sequence "\u001b[1;5C")

# For my home dir executables:
export PATH="$PATH:$HOME/bin"

# For Cursor:
# export PATH="$PATH:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin"
export PATH="$PATH:/Applications/Cursor.app/Contents/Resources/app/bin"

# For Pixi:
export PATH="$PATH:/Users/elliotwaite/.pixi/bin"
eval "$(pixi completion --shell zsh)" # Adds completions.

# For Bun:
export BUN_INSTALL="$HOME/.bun"
export PATH="$PATH:$BUN_INSTALL/bin"
[ -s "/Users/elliotwaite/.bun/_bun" ] && source "/Users/elliotwaite/.bun/_bun" # Adds completions.

# For Deno:
export DENO_INSTALL="/Users/elliotwaite/.deno"
export PATH="$PATH:$DENO_INSTALL/bin"

# For Nim:
export PATH="$PATH:$HOME/.nimble/bin"

# For Docker:
export PATH="$PATH:$HOME/.docker/bin"

# For EdgeDB:
export PATH="$PATH:$HOME/Library/Application Support/edgedb/bin"

# For Tauri mobile:
export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
export ANDROID_HOME="$HOME/Library/Android/sdk"
export NDK_HOME="$ANDROID_HOME/ndk/25.0.8775105"

# For React Native:
export REACT_EDITOR="pycharm"

# For Expo Android emulator (see: https://docs.expo.dev/workflow/android-studio-emulator/):
export ANDROID_SDK="$HOME/Library/Android/sdk"
export PATH="$PATH:$HOME/Library/Android/sdk/emulator"
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"
export PATH="$PATH:$HOME/Library/Android/sdk/tools"

# For Google Cloud SDK:
if [ -f "/Users/elliotwaite/sdks/google-cloud-sdk/path.zsh.inc" ]; then . "/Users/elliotwaite/sdks/google-cloud-sdk/path.zsh.inc"; fi # Updates PATH.
if [ -f "/Users/elliotwaite/sdks/google-cloud-sdk/completion.zsh.inc" ]; then . "/Users/elliotwaite/sdks/google-cloud-sdk/completion.zsh.inc"; fi # Adds completions.

# For Frum (Ruby version manager):
eval "$(frum init)"

# Aliases for Pixi:
alias pixup="pixi self-update"

# Aliases for Bun:
alias b="bun"
alias bup="bun upgrade"
# alias d="bun run --bun dev"
# alias dip="bun run --bun dev-ip"
# alias build="bun run --bun build"
# alias start="bun run --bun start"
# alias t="bun run --bun test"
# alias add="bun add -E"

# Aliases for PNPM:
alias p="pnpm"
alias i="pnpm i"
alias up="pnpm update --latest"
alias pup="curl -fsSL https://get.pnpm.io/install.sh | sh -"
alias d="pnpm dev"
alias dip="pnpm dev-ip"
alias build="pnpm build"
alias s="pnpm start"
alias t="pnpm test"
alias add="pnpm add -E"

#-------------------------------------------------------------------------------
